import { NextRequest, NextResponse } from "next/server";
import { Resend } from "resend";

const getResendClient = () => {
  const apiKey = process.env.RESEND_API_KEY;
  if (!apiKey || apiKey === "placeholder") return null;
  return new Resend(apiKey);
};

export async function POST(request: NextRequest) {
  try {
    const body = await request.json();
    const { to, subject, document_number, client_name, html_content } = body;

    if (!to || !subject || !html_content) {
      return NextResponse.json(
        { error: "Missing required fields: to, subject, html_content" },
        { status: 400 }
      );
    }

    // Validate email
    const emailRegex = /^[^\s@]+@[^\s@]+\.[^\s@]+$/;
    if (!emailRegex.test(to)) {
      return NextResponse.json(
        { error: "Invalid email address" },
        { status: 400 }
      );
    }

    const resend = getResendClient();

    if (!resend) {
      return NextResponse.json(
        {
          error: "Email service not configured. Add RESEND_API_KEY to .env.local",
          demo: true,
        },
        { status: 503 }
      );
    }

    const { data, error } = await resend.emails.send({
      from: "BillCraft <noreply@billcraft.in>",
      to: [to],
      subject: subject || `${document_number} from BillCraft`,
      html: `
        <div style="font-family:'Segoe UI',system-ui,sans-serif;max-width:600px;margin:0 auto;">
          <div style="background:#0a0a0a;padding:24px;border-radius:12px 12px 0 0;">
            <h1 style="color:#f59e0b;font-size:20px;margin:0;">BillCraft</h1>
          </div>
          <div style="padding:24px;background:#ffffff;border:1px solid #eee;">
            <p style="color:#333;font-size:14px;line-height:1.6;">
              Hi${client_name ? ` ${client_name}` : ""},
            </p>
            <p style="color:#333;font-size:14px;line-height:1.6;">
              Please find the attached ${document_number ? `document (${document_number})` : "document"} below.
            </p>
            <div style="margin:24px 0;padding:20px;background:#fafafa;border-radius:8px;border:1px solid #eee;">
              ${html_content}
            </div>
            <p style="color:#888;font-size:12px;margin-top:24px;">
              Generated by <a href="https://billcraft.vercel.app" style="color:#f59e0b;">BillCraft</a> — AI Invoice & Proposal Generator
            </p>
          </div>
        </div>
      `,
    });

    if (error) {
      console.error("Resend error:", error);
      return NextResponse.json(
        { error: "Failed to send email. Please try again." },
        { status: 500 }
      );
    }

    return NextResponse.json({ success: true, messageId: data?.id });
  } catch (error) {
    console.error("Email error:", error);
    return NextResponse.json(
      { error: "Failed to send email." },
      { status: 500 }
    );
  }
}
